### PR TITLE
Add checking for the existence of representative transcript

### PR DESCRIPTION
**Pull request by LeiChen0218**
Usage:
civic-api-client variants-list --no-rep-trans 
Notes:
Report variants only without representative transcript.

### CODE REVIEW

**Comment by malachig** [comment]
Hi @LeiChen0218 . Can we concatenate the errors into a comma separated list and include it on the same line as the rest of the output please?

**Comment by LeiChen0218** [comment]
Sure.
It should work as that now.

On Feb 25, 2016, at 5:39 PM, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @LeiChen0218https://github.com/LeiChen0218 . Can we concatenate the errors into a comma separated list and include it on the same line as the rest of the output please?

**Comment by LeiChen0218** [comment]
Hey guys,
Just added some new commits to this branch, and now it should include check functions for #5,#6,#7.

Usage for #5 and #6:

```
civic-api-client variants-list --rep-trans --transcript-file  $PATH/transcript.txt.gz
```

Notes: It will check three unpleasing status of representative transcripts: 1. Missing, 2. Wrong format, 3. Invalid (not in reference file). If the transcript file wasn't specified, then it won't check the 3rd part.
Usage for #7:

```
civic-api-client variants-list --ensembl-version
```

Notes: Given there's a representative transcript, It will check two errors of Ensembl version: 1. Missing, 2. Wrong format (not a int)

Just for the record, I didn't find type 3 error for rep. transcripts, and for all variants with existing rep. transcripts, there seemed to be nothing wrong about Ensembl version.  

Please take a look and help me with double check. @gatoravi @malachig

**Comment by gatoravi** [comment]
Ok, I verified that this works.. Looks great to me, @malachig might want to try this out as well.

**Comment by malachig** [comment]
Seems to be working nicely, though I'm a bit surprised that there are no variants with a missing version number...

**Comment by LeiChen0218** [comment]
Well, I remember there was some…
Was there any variant with error type “Wrong transcript format”? If there’s missing version number in a variant’s transcript then it should report this.

On Mar 1, 2016, at 5:26 PM, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

Seems to be working nicely, though I'm a bit surprised that there are no variants with a missing version number...

**Comment by LeiChen0218** [comment]
A new commit was added which has:
1. Check for Rep. transcript2 when there's second coordinate
2. Add ''_" when display errors ("Ref base"->"Ref_base")
3. Delete the extra "," followed by all error types
4. If there's second coordinate, automatically ignore the  check for wrong base
@gatoravi @malachig

**Comment by gatoravi** [comment]
:+1:  that's great! As a side-note, in the future if you like, each of these features could be separate commits.

**Comment by malachig** [comment]
This seems to be working nicely.  Let's go ahead and merge this one.

**Pull request merged**
