### PR TITLE
Add tsv-creat function to pull out all evidence items

### PR DESCRIPTION
**Pull request by LeiChen0218**
@gatoravi @obigriffith @malachig 
Just created a module to pull out all variants for UCSC Genome Browser track

Usage:

```
civic-api-client tsv-creat
```

Format is according to (but new columns are added):
https://civic.genome.wustl.edu/#/releases
Nightly
ClinicalEvidenceSummaries.tsv

### CODE REVIEW

**Comment by obigriffith** [comment]
The output looks good so far. Some suggestions/questions:
1. Drop pubchem_ids as this is always empty, no longer supported, and should be dropped from the download page version as well.
2. Add gene_civic_url
3. After the rating column we should add evidence_status so that @maximilianh can filter out evidence statements that have been rejected. Or, we can do this on our end.
4. We should also add variant origin to each record.
5. Any idea why it comes up with one less evidence item than reported on the main/admin CIViC pages (1008 vs 1009)?

**Comment by LeiChen0218** [comment]
While other issues are being solved, I may have found the answer to 5th question:
On civic webpage, the evidence number of BRAF is reported as 44, while actually after counting through all variants, there’re only 43 evidences:
AGK-BRAF        2
AKAP9-BRAF      1
L597R   1
MUTATION        2
PAPSS1-BRAF     2
TRIM24-BRAF     1
V600    5
V600D   1
V600E   25
V600E AMPLIFICATION     1
V600E+V600M     1
WILD TYPE      1

So I guess somebody might want to check this gene (gene id:5).

Lei

  *

**Comment by kkrysiak** [comment]
There are 43 evidence statements everywhere I look but in the gene browse page. There aren't any rejected evidence items either. This definitely warrants some more investigation.

**Comment by obigriffith** [comment]
Looks good. A couple minor issues remain:
1. some variant summaries are quoted and start with u"
2. evidence statements are in consistently quoted.
3. variant summaries are also inconsistently quoted.

**Comment by maximilianh** [comment]
Is that quoting intentional? I have the impression that real "quotes" from
documents have quotes around them. If it's a summary someone has typed,
it's not quoted. That at least was my hypothesis based on looking at the
data.

It would be awesome if variants ALWAYS had a literal quote from a paper. I
really like this feature, being able to trace a statement back to the
original paragraph. Hardly any database does it like that and so you often
have to dig into the paper to figure out why the curator made some
inference.

**Comment by obigriffith** [comment]
I wish I could say it was. But, no, the quoting is just a function of the way data is being stored, output, or escaped. I agree that a literal quote would be awesome. When we started CIViC we seriously considered this. The challenge we had was that we were trying to create short, human readable summaries of papers and balancing the desire for comprehensive curation against the "curation hump". I.e., If a single curation task is too daunting it is very difficult to get people to actually do it. So, we have continually tried to keep the minimum requirements for a CIViC entry minimal. Also, we found that to quote the relevant part(s) of the paper you often end up quoting large sections of the paper, multiple sentences throughout the paper, portions of figure captions, etc. This starts to create concerns of copyright infringement, redistributing content without permission, etc. If we are just reporting a summary of the work in our own words this is not an issue.

**Comment by LeiChen0218** [comment]
Those quoting and u' should be eliminated in the latest version @obigriffith @maximilianh

**Comment by LeiChen0218** [comment]
Hey guys, do you think we can merge this branch now? @obigriffith @gatoravi

**Comment by malachig** [comment]
I think we can go ahead and merge now.  If we hear about further issues from @maximilianh we can open a new issue or PR.

**Pull request merged**
