### PR TITLE
Fixed bugs in variant lister module

### PR DESCRIPTION
**Pull request by LeiChen0218**
1. Add Error type report
2. Report all variants with errors without any flag specified (It used to report all variants with or without errors)
3. Fixed the bugs when extracting var_base and ref_base information

The usage is the same with previous version.

### CODE REVIEW

**Comment by malachig** [comment]
Now when I run this `civic-api-client variants-list --no-coords --max-gene-count 10` I get results for every variant, even if coordinates are already defined.  We just want to see the variants where coordinates are missing...

**Comment by LeiChen0218** [comment]
Sorry. It should be fixed now, check again?

On Feb 24, 2016, at 4:26 PM, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

Now when I run this civic-api-client variants-list --no-coords --max-gene-count 10 I get results for every variant, even if coordinates are already defined. We just want to see the variants where coordinates are missing...

**Comment by malachig** [comment]
Okay, seems to be working now.  @gatoravi okay to merge this?

**Comment by gatoravi** [comment]
I don't think I understand what happens when multiple options such as `--wrong-base` AND `--wrong-base` are specified by a user. Will a variant have to satisfy BOTH the conditions to be outputted or would any one condition suffice?

**Comment by LeiChen0218** [comment]
Either condition will be reported.

Sent from my iPhone

On Feb 25, 2016, at 10:21, Avi Ramu <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't think I understand what happens when multiple options such as --wrong-base AND --wrong-base are specified by a user. Will a variant have to satisfy BOTH the conditions to be outputted or would any one condition suffice?

##

**Comment by gatoravi** [comment]
:+1: I think I get it now!

**Comment by malachig** [comment]
Okay, Lei.  Lets go ahead and merge this one and then talk about the next issue to tackle.  I think #5, #6, and #7 are all related and perhaps the next lowest hanging fruit.  And from a curation perspective we know there are some inconsistencies there.

**Comment by LeiChen0218** [comment]
Sure. I'll be there in half an hour.

On Feb 25, 2016, at 11:15, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay, Lei. Lets go ahead and merge this one and then talk about the next issue to tackle. I think #5https://github.com/griffithlab/civic-api-client/issues/5, #6https://github.com/griffithlab/civic-api-client/issues/6, and #7https://github.com/griffithlab/civic-api-client/issues/7 are all related and perhaps the next lowest hanging fruit. And from a curation perspective we know there are some inconsistencies there.

##

**Comment by LeiChen0218** [comment]
A new branch called add-rep-transcript-checkhttps://github.com/griffithlab/civic-api-client/tree/add-rep-transcript-check  is a first try of fixing issue #5.
Here’s a limitation of current version of variant-lister: when there’re several errors happened in the same variant, it only reports the first error identified.
I can modify it to report several errors, but for errors like —no-coords and —wrong-base/ —no-coords and —no-rep-trans, they’re actually not independent (No-coordinates means ref_base and var_base will be none, which also meets the criteria of wrong-base).
So do you guys think it will be better to make that change?

Lei

On Feb 25, 2016, at 11:15 AM, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay, Lei. Lets go ahead and merge this one and then talk about the next issue to tackle. I think #5https://github.com/griffithlab/civic-api-client/issues/5, #6https://github.com/griffithlab/civic-api-client/issues/6, and #7https://github.com/griffithlab/civic-api-client/issues/7 are all related and perhaps the next lowest hanging fruit. And from a curation perspective we know there are some inconsistencies there.

**Comment by malachig** [comment]
I think it is fine to report multiple errors even if some are related to each other.

**Comment by LeiChen0218** [comment]
Now it will give all errors of a variant.

On Feb 25, 2016, at 3:57 PM, Malachi Griffith <notifications@github.com<mailto:notifications@github.com>> wrote:

I think it is fine to report multiple errors even if some are related to each other.

**Pull request merged**
